kafka:
  endpoint: "localhost"
topics:
  - name: values
    encoding: makinage.encoding.string
  - name: multiplied_values
operators:
  multiply:
    factory: makinage.sample.processor:multiply
    sources:
      - values
    sinks:
      - multiplied_values
config:
  multiply: 3