application:
  name: my_model_serving
kafka:
  endpoint: "localhost"
topics:
  - name: data
    encoder: makinage.encoding.json
  - name: model
    encoder: makinage.encoding.none
    start_from: last
  - name: predict
    encoder: makinage.encoding.json
operators:
  serve:
    factory: makinage.serve:serve
    sources:
      - model
      - data      
    sinks:
      - predict
config:
  serve:
    - input_field: x
    - output_field: pred